# TODO: This config file is in the old format. We need to make it match debug.yaml
defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: bleu,wer
  preproc:
    overwrite: False
    preproc_specs:
    #- type: tokenize
    #  in_files:
    #  - examples/data/train.ja
    #  - examples/data/dev.ja
    #  - examples/data/test.ja
    #  out_files:
    #  - examples/data/train.tok.ja
    #  - examples/data/dev.tok.ja
    #  - examples/data/test.tok.ja
    #  specs:
    #  - filenum: all
    #    tokenizers:
        #- !ExternalTokenizer
          # Replace <XNMT_PATH> with root directory of xnmt repository
    #      path: /Users/cindywang/Documents/research/TSG/xnmt/script/code/toy_word_tokenize.py
    #      tokenizer_args: 
    #        --character: 0
    #    - !SentencepieceTokenizer
          # Replace <SENTENCEPIECE_SRC_PATH> with src/ directory of sentencepiece repository
          # The spm_* executables should be located at <SENTENCEPIECE_SRC_PATH>
    #      path: /Users/cindywang/Documents/research/TSG/code/sentencepiece/src/
    #      train_files:
    #       - examples/data/train.ja
    #       - examples/data/train.en
    #      vocab_size: 20000
    #      model_type: bpe
    #- type: normalize
    #  in_files:
    #  - examples/data/train.tok.ja
    #  - examples/data/train.en
    #  - examples/data/dev.tok.ja
    #  - examples/data/dev.en
    #  - examples/data/test.tok.ja
    #  - examples/data/test.en
    #  out_files:
    #  - examples/output/train.norm.ja
    #  - examples/output/train.norm.en
    #  - examples/output/dev.norm.ja
    #  - examples/output/dev.norm.en
    #  - examples/output/test.norm.ja
    #  - examples/output/test.norm.en
    #  specs:
    #  - filenum: all
    #    spec:
    #    - type: lower
    #- type: filter
    #  in_files:
    #  - examples/output/train.norm.ja
    #  - examples/output/train.norm.en
    #  out_files:
    #  - examples/output/train.filter.ja
    #  - examples/output/train.filter.en
    #  specs:
    #  - type: length
    #    min: 1
    #    max: 25
    - type: vocab
      in_files:
      - /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-train.cln.piece.ja
      - /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-train.cln.en
      out_files:
      - examples/output/kyoto-train.cln.piece.vocab.ja
      - examples/output/kyoto-train.cln.vocab.en
      specs:
      - filenum: all
        spec:
        - type: freq
          min_freq: 2
  train:
    default_layer_dim: 512
    restart_trainer: True
    trainer: Adam
    learning_rate: 0.0002
    lr_decay: 0.5
    dev_metrics: bleu
    batch_size: 16
    training_corpus: !BilingualTrainingCorpus
      train_src: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-train.cln.piece.ja
      train_trg: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-train.cln.en
      dev_src: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-dev.piece.ja
      dev_trg: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-dev.en
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader
        vocab: !Vocab
          vocab_file: examples/output/kyoto-train.cln.piece.vocab.ja
      trg_reader: !PlainTextReader
        vocab: !Vocab
          vocab_file: examples/output/kyoto-train.cln.vocab.en
    model: !DefaultTranslator
      src_embedder: !SimpleWordEmbedder
        emb_dim: 512
      encoder: !LSTMEncoder
        layers: 1
        hidden_dim: 1024
      attender: !StandardAttender
        hidden_dim: 512
        state_dim: 512
        input_dim: 1024
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 512
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 512
        input_feeding: True
        bridge: !LinearBridge
          dec_layers: 1
          enc_dim: 1024
          dec_dim: 512
  decode:
    src_file: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-test.piece.ja
    beam: 5
  evaluate:
    ref_file: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/tok/kyoto-test.en

baseline-enja-large:
  train:
    dropout: 0.0
