defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    cfg_file: examples/output/<EXP>.yaml
    run_for_epochs: 20
    eval_metrics: bleu
  train:
    dropout: 0.1
    default_layer_dim: 512
    restart_trainer: True
    trainer: Adam
    learning_rate: 0.0002
    lr_decay: 0.5
    dev_metrics: bleu
    training_corpus: !BilingualTrainingCorpus
      train_src: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-train.uppiece.ja
      train_trg: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-train.uppiece.en
      dev_src: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-tune.uppiece.ja
      dev_trg: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-tune.uppiece.en
      dev_ref_file: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-tune.upper.en
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !PlainTextReader {}
    model: !DefaultTranslator
      src_embedder: !SimpleWordEmbedder {}
      encoder: !LSTMEncoder
        layers: 1
      attender: !StandardAttender {}
      trg_embedder: !SimpleWordEmbedder {}
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 512
        bridge: !CopyBridge {}
  decode:
    beam: 5
    post_process: join-piece
    len_norm_type: !PolynomialNormalization
      apply_during_search: true
    src_file: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-tune.uppiece.ja
  evaluate:
    ref_file: /projects/tir2/users/xinyiw1/kftt-data-1.0/data/small/kyoto-tune.upper.en

kftt-std-small:
