defaults:
  experiment:
    model_file: oromo/output/<EXP>.mod
    hyp_file: oromo/output/<EXP>.hyp
    out_file: oromo/output/<EXP>.out
    err_file: oromo/output/<EXP>.err
    cfg_file: oromo/output/<EXP>.yaml
    run_for_epochs: 30
    eval_metrics: bleu
  train:
    batcher: !SrcBatcher
      batch_size: 16
    #dev_every: 50000
    dropout: 0.
    default_layer_dim: 512
    restart_trainer: False
    trainer: Adam
    learning_rate: 0.001
    lr_decay: 1.0
    attempts_before_lr_decay: 5
    dev_metrics: bleu
    schedule_metric: bleu
    training_corpus: !BilingualTrainingCorpus
      train_src: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.piece.orm
      train_trg: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.parse.eng,/projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.piece.eng
      train_len_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.piece.eng
      dev_src: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.piece.orm
      dev_trg: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.parse.eng,/projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.piece.eng
      dev_ref_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.eng
      dev_len_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.piece.eng
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !TreeReader 
        binarize: False
        del_preterm_POS: True
        read_word: True
        merge: False
    model: !DefaultTranslator
      loop_trg: True
      src_embedder: !SimpleWordEmbedder {}
      trg_embedder: !SimpleWordEmbedder {}
      word_embedder: !SimpleWordEmbedder {}
      encoder: !LSTMSeqTransducer
        layers: 1
      attender: !StandardAttender {}
      word_attender: !StandardAttender {}
      decoder: !TreeHierDecoder
        layers: 1
        mlp_hidden_dim: 512
        bridge: !CopyBridge {}
        start_nonterm: ROOT
  decode:
    beam: 6
    post_process: rule-piece
    max_len: 200
    len_norm_type: !PolynomialNormalization
      apply_during_search: true
      m: 2.
    src_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-test.nltk.piece.orm
  evaluate:
    ref_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-test.nltk.eng

#kftt-tree-hier-2:
#  train:
#    pretrained_model_file: kftt/output/kftt-tree-hier.mod

oromo-tree-hier-nodrop:
  #train:
  #  pretrained_model_file: kftt/output/kftt-tree-hier-0.5.mod
