defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    cfg_file: examples/output/<EXP>.yaml
    run_for_epochs: 50
    eval_metrics: bleu
  train:
    dropout: 0.2
    default_layer_dim: 512
    restart_trainer: False
    trainer: Adam
    learning_rate: 0.001
    attempts_before_lr_decay: 5
    lr_decay: 0.5
    dev_metrics: bleu
    schedule_metric: bleu
    batcher: !SrcBatcher
      batch_size: 64
    training_corpus: !BilingualTrainingCorpus
      train_src: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.piece.orm
      train_trg: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-train.nltk.piece.eng
      dev_src: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.piece.orm
      dev_trg: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.piece.eng
      dev_ref_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-dev.nltk.eng
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !PlainTextReader {}
    model: !DefaultTranslator
      src_embedder: !SimpleWordEmbedder {}
      encoder: !LSTMSeqTransducer
        layers: 1
      attender: !StandardAttender {}
      trg_embedder: !SimpleWordEmbedder {}
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 512
        bridge: !CopyBridge {}
  decode:
    beam: 5
    post_process: join-piece
    len_norm_type: !PolynomialNormalization
      apply_during_search: true
    src_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-test.nltk.piece.orm
  evaluate:
    ref_file: /projects/tir2/users/xinyiw1/loreili/orm-eng/data/set0-test.nltk.eng

oromo-seq-64:
